# Generated by Django 4.1 on 2022-09-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70, verbose_name='Имя клиента')),
                ('organisation', models.TextField(verbose_name='Название организации')),
                ('number_of_account', models.PositiveIntegerField(verbose_name='Номер счета')),
                ('sum', models.IntegerField(verbose_name='Сумма')),
                ('service', models.TextField(verbose_name='Справочник')),
                ('date', models.DateField(verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Счет',
                'verbose_name_plural': 'Счета',
                'db_table': 'Account',
                'unique_together': {('name', 'number_of_account', 'organisation')},
            },
        ),
    ]
