# Generated by Django 4.1 on 2022-09-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='sum',
            field=models.FloatField(verbose_name='Сумма'),
        ),
    ]
